version: '3.8'

services:
  # Next.js Frontend
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV: development
      - NEXT_PUBLIC_API_URL: http://localhost:3000
      - MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/skill_sculptor?authSource=admin
      - JWT_SECRET: ${JWT_SECRET}  # Read from .env
      - GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      - mongo
    command: npm run dev

mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=skill_sculptor

volumes:
  mongo_data: