version: '3.8'

services:
  # Next.js Frontend
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      # - /app/.next
    environment:
      -  NODE_ENV: development
      - NEXT_PUBLIC_API_URL: http://localhost:3000
      - MONGODB_URI: mongodb://mongo:27017/skill_sculptor
      - JWT_SECRET: your-super-secret-jwt-key-here
    depends_on:
      - mongo
    command: npm run dev

  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB: skill_sculptor
      - POSTGRES_USER: user
      - POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "5432:5432"

  # Redis для кешування та сесій
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # pgAdmin для управління базою даних (опціонально)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL: admin@example.com
      - PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  postgres_data:
  redis_data: